version: '2.3'
services:
  nest-api:
    hostname: nest-api
    image: valentinconan/nest-api-native:master
    restart: unless-stopped
    healthcheck:
      test: wget -O /dev/null http://localhost:3000/health || exit 1
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "3000:3000"
    networks:
      - nest-network
networks:
  nest-network:
    driver: bridge